"""initial

Revision ID: 1e092fb87ed5
Revises: 
Create Date: 2022-12-05 14:23:07.059624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e092fb87ed5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books_authors')
    op.drop_table('authors')
    op.drop_table('books')
    op.drop_table('books_genres')
    op.drop_table('genres')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('genres_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('genre_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='genres_pkey'),
    sa.UniqueConstraint('genre_name', name='genres_genre_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('books_genres',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='books_genres_book_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name='books_genres_genre_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'genre_id', name='books_genres_pkey')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('books_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('book_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('number_of_pages', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reiting', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('authors',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('authors_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('author_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_surname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author_patronymic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('date_of_death', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='authors_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('books_authors',
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], name='books_authors_author_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name='books_authors_book_id_fkey'),
    sa.PrimaryKeyConstraint('book_id', 'author_id', name='books_authors_pkey')
    )
    # ### end Alembic commands ###
